### ISSUE TITLE
Génération ICC-API

### ISSUE THREAD

**Issue by dlm-nsi** [antoinepairet/icure-backend#15]
Bonjour Antoine,

Sur le repository taktik/icc-API nous avons trouvé par hasard un jar contenant la génération de code swagger. En exécutant celui-ci avec la commande suivante :
java %JAVA_OPTS% -cp swagger-codegen-cli.jar io.swagger.codegen.SwaggerCodegen generate -i http://localhost:16043/rest/v1/swagger.json  -l typescript -o medispring

On obtients une génération quasi identique à ce qui se trouve sur leur repository, a l’exception du fait que le préfixe n’est pas icc mais swg.
J’ai essayé de créer une issue sur ton REPO /icc-appi mais sans succès (option indisponible vu que je ne suis pas contributeur ?).

Que devons-nous faire pour avoir une génération du code fonctionnelle et compatible avec taktik/b12 ? 

Bien à toi,

**Comment by antoinepairet** [comment]
Pour regénérer les fichiers de `icc-api`, il faut lancer

- `icure.cloud` => `npm run gen`
- `version locale` => `npm run genloc`
