### ISSUE TITLE
Intégration Travis

### ISSUE THREAD

**Issue by dlm-nsi** [antoinepairet/icure-backend#24]
Hi Antoine,

I have done a travis yml which do the build of the application as I was asked by julien. 
If you can confirm that I can put the yml on a branch made from development I would be glad.

I have attached the yml file in question.

Kr,

David.

![travis](https://user-images.githubusercontent.com/40821489/46667611-6ef23700-cbca-11e8-87bd-22becc7b70dd.PNG)
[.travis.yml.txt](https://github.com/antoinepairet/icure-backend/files/2460237/default.travis.yml.txt)

**Comment by antoinepairet** [comment]
@dlm-nsi 
Peux-tu faire une PR avec le fichier travis?

Thanks
